CREATE TABLE IF NOT EXISTS public.regras (
    id BIGSERIAL PRIMARY KEY,
    tipo_profissional VARCHAR(255) NOT NULL,
    tipo_dia VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.regra_blocos (
    id BIGSERIAL PRIMARY KEY,
    regra_id BIGINT NOT NULL,
    bloco_id BIGINT NOT NULL,
    qtd_manha INT DEFAULT 0,
    qtd_tarde INT DEFAULT 0,
    qtd_noite INT DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_regra FOREIGN KEY(regra_id) REFERENCES public.regras(id) ON DELETE CASCADE,
    CONSTRAINT fk_bloco FOREIGN KEY(bloco_id) REFERENCES public.blocos(id) ON DELETE CASCADE
);
